---
- name: Proxmox Create VM(s) from template
  hosts: localhost
  gather_facts: false

  vars:
    proxmox_cluster_host: "proxmox-cluster-host"
    proxmox_target_node: "proxmox-target-node"
    proxmox_node_storage: "proxmox-node-storage"

    vm_guests_to_create: [{hostname: "vm-test-001", vmid: 800}, {hostname: "vm-test-002", vmid: 801}]
    template: "image-base"

  vars_prompt:
    - name: proxmox_api_user
      prompt: "Proxmox API User"
      default: "root@pam"
      private: false

    - name: proxmox_api_secret
      prompt: "Proxmox API Secret"
      unsafe: true
      private: true
      confirm: true

  tasks:
    - name: Async Create VM(s)
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_secret }}"
        api_host: "{{ proxmox_cluster_host }}"
        node: "{{ proxmox_target_node }}"
        clone: "{{ template }}"
        full: true
        storage: "{{ proxmox_node_storage }}"
        name: "{{ item.hostname }}"
        newid: "{{ item.vmid }}"
        state: "present"
        timeout: 600
      with_items: "{{ vm_guests_to_create }}"
      register: create_vm_results
      async: 600
      poll: 0

    - name: Wait for all VM(s) to finish creating
      ansible.builtin.async_status:
        jid: "{{ item.ansible_job_id }}"
      register: vm_create_job_result
      until: vm_create_job_result.finished
      retries: 300
      delay: 5
      with_items: "{{ create_vm_results.results }}"
