---
- name: Patch Guest VM (dnf)
  hosts: all
  gather_facts: false
  become: true

  tasks:

    - name: Update DNF Packages
      ansible.builtin.dnf:
        name: "*"
        update_cache: true
        state: "latest"
      notify:
       - Reboot Host

  handlers:
    - name: Reboot Host
      ansible.builtin.reboot:
        msg: "OS Patching completed, rebooting"
        reboot_timeout: 1800
